# Generated by Django 4.2.1 on 2025-09-18 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_telefone', message='número inválido! Use o formato DDD + número ', regex='^\\d{2}9\\d{8}$')])),
            ],
        ),
    ]
